services:
  bot:
    build:
      context: .
    container_name: 'AiogramShopBot'
    environment:
      WEBHOOK_PATH: ""
      WEBAPP_HOST: "0.0.0.0" # Don't touch this
      WEBAPP_PORT: 5000 # Here your port
      TOKEN: "1234567890:QWER.....TYI" # Here your bot token from botfather
      NGROK_TOKEN: 'NGROK_TOKEN_HERE' # Here your ngrok token from ngrok.com
      ADMIN_ID_LIST: "12345678,87654321" # Telegram ID's for admins;
      SUPPORT_LINK: "https://t.me/YourUsername"
      DB_NAME: "database.db" # Here your database name
      DB_PASS: "1234567" # Here your database password
      PAGE_ENTRIES : 8
      BOT_LANGUAGE: "en"
      MULTIBOT: "false"
      ETHPLORER_API_KEY: "" # API key from Ethplorer
    ports:
      - "4040:4040"
      - "5000:5000" # ${WEBAPP_PORT}:${WEBAPP_PORT}
    expose:
      - 4040
      - 5000 # ${WEBAPP_PORT}
    volumes:
      - ./AiogramShopBot:/bot/data # endswith your database name
    command: ["python", "-u", "run.py"]

volumes:
  AiogramShopBot: